### ISSUE TITLE
Image source for coins changed.

### ISSUE THREAD

**Issue by HamzaAnis** [jsnomad/ionic-cryptocurrency#1]
The source for the coin images is changed from
[https://files.coinmarketcap.com/static/img/coins/32x32/](here)
to 
[https://s2.coinmarketcap.com/static/img/coins/32x32/](here)

They have also changed the image names e.g
For BTC is is
https://s2.coinmarketcap.com/static/img/coins/32x32/1.png
and for ETH it is
https://s2.coinmarketcap.com/static/img/coins/32x32/1027.png
before it was across their id's.

**Comment by jsnomad** [comment]
Thank you for opening this issue.
I've fixed it using [this repo](https://github.com/cjdowner/cryptocurrency-icons) as you suggested in your pull request 😉.

**Comment by HamzaAnis** [comment]
Always welcome. :)
